name: app_environment
channels:
  - snowflake
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - numpy
      - matplotlib
      - scipy
      - SQLAlchemy
      - mysql-connector-python
      - streamlit
      - snowflake-connector-python
      - snowflake-snowpark-python
