name: app_env
channels:
  - snowflake
  - conda-forge
dependencies:
  - python=3.11
  - streamlit
  - snowflake-snowpark-python
  - pandas
  - numpy
  - matplotlib=3.7.2
  - scipy
  - sqlalchemy
  - pip
  - pip:
      - mysql-connector-python
      - snowflake-connector-python
