name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      HF_SPACE: jeanmarcocruz207/Tinka_Analytics
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push code to HF Space (overwrite safely)
        run: |
          set -e
          git config user.email "action@github.com"
          git config user.name  "GitHub Action"
          git lfs install
          git remote remove hub 2>/dev/null || true
          git remote add hub "https://jeanmarcocruz207:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}"
          git push hub main --force-with-lease
